<?php

namespace Jasuwienas\MailBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DateTime;
use Doctrine\ORM\QueryBuilder;
use Exception;

/**
 * MailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailQueueRepository extends EntityRepository
{

    /**
     * @return MailQueue|null
     */
    public function getFirstReadyToProcess() {
        try {
            return $this->createReadyToProcessQueryBuilder('queue')
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch(Exception $exception) {
            return null;
        }
    }

    /**
     * @param $queryName
     * @param null $indexBy
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createReadyToProcessQueryBuilder($queryName, $indexBy = null) {
        return $this->createQueryBuilder($queryName, $indexBy)
            ->andWhere($queryName . '.status in (:status)')
            ->andWhere($queryName . '.sendAt < :sendAt')
            ->setParameter('status', [MailQueue::STATUS_NEW, MailQueue::STATUS_TRY_AGAIN])
            ->setParameter('sendAt', new DateTime())
            ;
    }
}
