<?php

namespace Jasuwienas\MailBundle\Entity;

use Doctrine\ORM\EntityRepository;
use DateTime;
use Doctrine\ORM\QueryBuilder;
use Exception;

/**
 * MailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailQueueRepository extends EntityRepository
{

    /**
     * @return MailQueue|null
     */
    public function getFirstReadyToProcess() {
        try {
            return $this->createReadyToProcessQueryBuilder('queue')
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch(Exception $exception) {
            return null;
        }
    }


}
